version: 0.0
os: linux
files:
  - source: /build/libs/See-book-0.0.1-SNAPSHOT.jar
    destination: /home/ec2-user/SeeBook/

hooks:
  BeforeInstall:  # 배포 전에 애플리케이션 종료
    - location: scripts/stop.sh
      timeout: 300
      runas: ec2-user

  AfterInstall:   # 배포 후 애플리케이션 시작
    - location: scripts/start.sh
      timeout: 300
      runas: ec2-user